# Contexte 
Une entreprise dispose de plusieurs capteurs installés dans différents bâtiments. Les capteurs mesurent régulièrement la température, l'humidité, la pression et la consommation énergétique. 
Les données doivent être préparées et analysées avant d'être transmises à un futur système de Machine Learning permettant de détecter des situations anormales 


In [29]:
# Importation de bibliothèque numpy
import numpy as np

# Partie 1 : Listes Python vs tableaux NumPy 

On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8 

## 1)	Créer une liste Python stockant ces températures; 

In [18]:
temperature = [24.5, 25.1, 26.3, 27.0, 25.8]
print("Temperature readings:", temperature)

Temperature readings: [24.5, 25.1, 26.3, 27.0, 25.8]


## 2)	Créer un tableau NumPy équivalent stockant ces températures ; 

In [19]:
temperature_tab = np.array(temperature)
temperature_tab

array([24.5, 25.1, 26.3, 27. , 25.8])

## 3)	Effectuer une multiplication par 2 sur ces deux collections ; 

In [20]:
# multiplication par 2 pour la liste
temperature_X2 = temperature * 2
temperature_X2

[24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]

# Partie 2 – Création des données 

## 1)	Créer un tableau représentant les mesures de température de 10 capteurs, initialement à zéro. 

In [22]:
# Températures de 10 capteurs, initialement à zéro
temp_10_capteurs = np.zeros(10)
print(temp_10_capteurs)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 2)Créer un tableau contenant 10 valeurs égales à 1. 

In [23]:
# Tableau de 10 valeurs egales à 1
temp_10_capteurs_1 = np.ones(10)
print(temp_10_capteurs_1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## 3)Créer un tableau de 10 valeurs initialisées à 25. 

In [24]:
# Tableau de 10 valeurs initialisées à 25
temp_10_capteurs_25 = np.full(10, 25)
print(temp_10_capteurs_25)

[25 25 25 25 25 25 25 25 25 25]


## 4)Créer une matrice identité de taille 5 × 5. 

In [26]:
# creation de la matrice identité 5x5
matrice_identite = np.eye(5)
print(matrice_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 5)Créer les 24 heures (de 0 à 23) de mesure d’une journée 

In [27]:
# creation des 24 heures (de 0 à 23) de mesure d'une journée
heures = np.arange(24)
print(heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


## 6)Créer 10 valeurs régulièrement réparties entre 20 °C et 30 °C  

In [28]:
# 10 valeurs régulièrement réparties entre 20 et 30
temp_10_capteurs_20_30 = np.linspace(20, 30, 10)
print(temp_10_capteurs_20_30)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


## 7)Créer aléatoirement les températures de 100 mesures, en rendant les résultats reproductibles 

In [34]:
# creation aleatoirement des temperatures de 100 mesures, rendant les resultats reproductibles
np.random.seed(42)
temp_100_capteurs = np.random.uniform(20, 30, 100)
print(temp_100_capteurs)

[23.74540119 29.50714306 27.31993942 25.98658484 21.5601864  21.5599452
 20.58083612 28.66176146 26.01115012 27.08072578 20.20584494 29.69909852
 28.32442641 22.12339111 21.81824967 21.8340451  23.04242243 25.24756432
 24.31945019 22.9122914  26.11852895 21.39493861 22.92144649 23.66361843
 24.56069984 27.85175961 21.99673782 25.14234438 25.92414569 20.46450413
 26.07544852 21.70524124 20.65051593 29.48885537 29.65632033 28.08397348
 23.04613769 20.97672114 26.84233027 24.40152494 21.22038235 24.9517691
 20.34388521 29.09320402 22.58779982 26.62522284 23.11711076 25.20068021
 25.46710279 21.84854456 29.69584628 27.75132823 29.39498942 28.9482735
 25.97899979 29.21874235 20.88492502 21.95982862 20.45227289 23.25330331
 23.8867729  22.71349032 28.28737509 23.56753327 22.8093451  25.42696083
 21.40924225 28.02196981 20.74550644 29.86886937 27.72244769 21.98715682
 20.05522117 28.15461428 27.06857344 27.29007168 27.71270347 20.74044652
 23.58465729 21.1586906  28.63103426 26.23298127 23.30